export type Routine={
    id: string,
    slug: string,
    name: string,
    exercises: string[],
    duration: string,
    frequency: string,
    description: string,
    difficulty: string,
    warmup: string[];
    cooldown: string[];
    notes: string[];
}

export const Routines: Routine[] = [
    {
        id: "fullbody_beginner",
        slug: "fullbody_beginner",
        name: "Full Body Beginner",
        exercises: ["push-ups", "bodyweight-squat", "plank"],
        duration: "20 min",
        frequency: "3x per week",
        description: "A beginner-friendly full-body routine to build foundational strength.",
        difficulty: "Beginner",
        warmup: ["Arm circles", "Hip rotations", "Light jogging 2 min"],
        cooldown: ["Forward fold 30s", "Quad stretch 30s", "Deep breathing 1 min"],
        notes: ["Focus on clean form", "Rest 60–90s between exercises"],
    },
    {
        id: "upper_intermediate",
        slug: "upper_intermediate",
        name: "Upper Body Intermediate",
        exercises: ["pull-ups", "dips", "push-ups"],
        duration: "30 min",
        frequency: "3-4x per week",
        description: "Build upper-body strength with a balanced push–pull routine.",
        difficulty: "Intermediate",
        warmup: ["Scapular pull-ups", "Band shoulder warmup", "Wrist circles"],
        cooldown: ["Chest stretch", "Lat stretch", "Shoulder mobility routine"],
        notes: ["Try to reach near-failure on final sets"],
    },
    {
        id: "advanced_strength",
        slug: "advanced_strength",
        name: "Advanced Strength",
        exercises: ["muscle-up", "pull-ups", "dips", "push-ups"],
        duration: "45 min",
        frequency: "4-5x per week",
        description: "A challenging advanced routine targeting strength and power.",
        difficulty: "Advanced",
        warmup: ["Explosive push-ups", "Light band rows", "Dynamic shoulder mobility"],
        cooldown: ["Forearm stretch", "Thoracic extension drills"],
        notes: ["Keep rest times strict to maintain intensity"],
    },
    {
        id: "lower_beginner",
        slug: "lower_beginner",
        name: "Lower Body Beginner",
        exercises: ["bodyweight-squat", "pistol-squat", "plank"],
        duration: "25 min",
        frequency: "3x per week",
        description: "Beginner-focused lower-body routine.",
        difficulty: "Beginner",
        warmup: ["Leg swings", "Ankle mobility", "Glute activation"],
        cooldown: ["Hamstring stretch", "Calf stretch"],
        notes: ["Prioritize knee alignment during squats"],
    },
    {
        id: "core_stability",
        slug: "core_stability",
        name: "Core & Stability",
        exercises: ["plank", "l-sit", "human-flag"],
        duration: "20 min",
        frequency: "3x per week",
        description: "Core-focused routine building static strength.",
        difficulty: "Intermediate",
        warmup: ["Hollow body rocks", "Wrist warmup", "Hip flexor activation"],
        cooldown: ["Lower back stretch", "Cat–cow"],
        notes: ["Move slowly and maintain tension throughout"],
    },
    {
        id: "push_strength",
        slug: "push_strength",
        name: "Push Strength",
        exercises: ["push-ups", "pike-push-ups", "dips", "archer-push-ups"],
        duration: "35 min",
        frequency: "3-4x per week",
        description: "Chest, shoulder, and triceps strength builder.",
        difficulty: "Intermediate",
        warmup: ["Scap push-ups", "Shoulder mobility", "Wrist circles"],
        cooldown: ["Triceps stretch", "Shoulder decompression"],
        notes: ["Control the eccentric phase on every rep"],
    },
    {
        id: "pull_strength",
        slug: "pull_strength",
        name: "Pull Strength",
        exercises: ["pull-ups", "chin-ups", "muscle-up"],
        duration: "40 min",
        frequency: "3-4x per week",
        description: "Pulling-focused routine for back, biceps, and explosiveness.",
        difficulty: "Intermediate",
        warmup: ["Scapular pull-ups", "Dead hangs", "Band rows"],
        cooldown: ["Lat stretch", "Forearm mobility"],
        notes: ["Use false grip work if aiming for muscle-ups"],
    },
    {
        id: "planche_progression",
        slug: "planche_progression",
        name: "Planche Progression",
        exercises: ["pseudo-planche-push-up", "planche-push-ups", "planche"],
        duration: "30 min",
        frequency: "4x per week",
        description: "Planche-focused static and strength training routine.",
        difficulty: "Advanced",
        warmup: ["Wrist mobility routine", "Scap protraction drills"],
        cooldown: ["Forearm stretches", "Chest opening drills"],
        notes: ["Expect slow progress — be patient"],
    },
    {
        id: "handstand_focus",
        slug: "handstand_focus",
        name: "Handstand & Overhead",
        exercises: ["pike-push-ups", "wall-handstand-push-ups", "handstand-push-ups", "plank"],
        duration: "30 min",
        frequency: "3-4x per week",
        description: "Improve overhead strength and handstand balance.",
        difficulty: "Intermediate",
        warmup: ["Wrist prep", "Shoulder opening", "Wall line drills"],
        cooldown: ["Neck stretch", "Shoulder decompression"],
        notes: ["Focus on stacking your hips over your wrists"],
    },
    {
        id: "explosive_upper",
        slug: "explosive_upper",
        name: "Explosive Upper",
        exercises: ["muscle-up", "pull-ups", "dips", "push-ups"],
        duration: "35 min",
        frequency: "3-4x per week",
        description: "Power-focused upper-body routine.",
        difficulty: "Advanced",
        warmup: ["Explosive push-ups", "Band warmup", "Shoulder activation"],
        cooldown: ["Lat stretch", "Chest opening"],
        notes: ["Use momentum sparingly—keep control"],
    },
    {
        id: "unilateral_balance",
        slug: "unilateral_balance",
        name: "Unilateral & Balance",
        exercises: ["pistol-squat", "one-arm-push-ups", "archer-push-ups", "l-sit"],
        duration: "40 min",
        frequency: "3x per week",
        description: "Single-limb strength and core control.",
        difficulty: "Advanced",
        warmup: ["Ankle mobility", "Shoulder prep", "Hip warmup"],
        cooldown: ["Hamstring stretch", "Glute stretch"],
        notes: ["Start with assisted variations if needed"],
    },
    {
        id: "advanced_fullbody",
        slug: "advanced_fullbody",
        name: "Advanced Full Body",
        exercises: ["planche", "human-flag", "muscle-up", "pistol-squat"],
        duration: "60 min",
        frequency: "5x per week",
        description: "Elite-level static and dynamic calisthenics routine.",
        difficulty: "Elite",
        warmup: ["Full wrist routine", "Dynamic shoulder mobility", "Core activation"],
        cooldown: ["Full-body stretch", "Deep breathing"],
        notes: ["Only attempt if you already master fundamentals"],
    },
    {
        id: "conditioning_circuit",
        slug: "conditioning_circuit",
        name: "Conditioning Circuit",
        exercises: ["push-ups", "pull-ups", "bodyweight-squat", "plank"],
        duration: "25 min",
        frequency: "4-5x per week",
        description: "A fast-paced circuit for general fitness.",
        difficulty: "Beginner",
        warmup: ["Light jogging", "Jumping jacks"],
        cooldown: ["Hamstring stretch", "Chest stretch"],
        notes: ["Try to avoid long breaks; keep heart rate up"],
    },
    {
        id: "mobility_recovery",
        slug: "mobility_recovery",
        name: "Mobility & Recovery",
        exercises: ["plank", "bodyweight-squat", "pike-push-ups"],
        duration: "20 min",
        frequency: "2-3x per week",
        description: "Low-intensity mobility routine for joint health.",
        difficulty: "Beginner",
        warmup: ["Light dynamic stretching"],
        cooldown: ["Deep breathing", "Full-body stretch"],
        notes: ["Ideal on rest days"],
    },
    {
        id: "grip_flag_progression",
        slug: "grip_flag_progression",
        name: "Grip & Flag Progression",
        exercises: ["human-flag", "pull-ups", "l-sit"],
        duration: "30 min",
        frequency: "3x per week",
        description: "Develop grip strength and core for flag variations.",
        difficulty: "Advanced",
        warmup: ["Wrist prep", "Dead hangs"],
        cooldown: ["Forearm stretch", "Lat stretch"],
        notes: ["Start from tucked progressions, slowly extend"],
    },
];

export default Routines;
