export type Routine={
    id: string,
    slug: string,
    name: string,
    exercises: string[],
    duration: string,
    frequency: string,
    description: string,
    difficulty: string,
    warmup: string[];
    cooldown: string[];
    notes: string[];
}

export const Routines: Routine[] = [
    {
        id: "fullbody_beginner",
        slug: "fullbody_beginner",
        name: "Full Body Beginner",
        exercises: ["push-ups", "bodyweight-squat", "plank"],
        duration: "20 min",
        frequency: "3x per week",
        description: "A complete beginner-friendly routine designed to build foundational strength using simple, accessible movements. It targets all major muscle groups evenly and helps establish proper form, control, and consistency before progressing into harder skills.",
        difficulty: "Beginner",
        warmup: ["Arm circles", "Hip rotations", "Light jogging 2 min"],
        cooldown: ["Forward fold 30s", "Quad stretch 30s", "Deep breathing 1 min"],
        notes: ["Focus on clean form", "Rest 60–90s between exercises"],
    },
    {
        id: "upper_intermediate",
        slug: "upper_intermediate",
        name: "Upper Body Intermediate",
        exercises: ["pull-ups", "dips", "push-ups"],
        duration: "30 min",
        frequency: "3-4x per week",
        description: "A balanced push–pull routine focused on developing stronger pulling mechanics, deeper pressing strength, and better shoulder stability. Ideal for lifters who can already handle basic calisthenics and want to push past plateaus.",
        difficulty: "Intermediate",
        warmup: ["Scapular pull-ups", "Band shoulder warmup", "Wrist circles"],
        cooldown: ["Chest stretch", "Lat stretch", "Shoulder mobility routine"],
        notes: ["Try to reach near-failure on final sets"],
    },
    {
        id: "advanced_strength",
        slug: "advanced_strength",
        name: "Advanced Strength",
        exercises: ["muscle-up", "pull-ups", "dips", "push-ups"],
        duration: "45 min",
        frequency: "4-5x per week",
        description: "A demanding routine built for advanced athletes aiming to increase raw upper-body strength, explosive power, and movement efficiency. Includes high-skill exercises that require control, intensity, and strong foundations.",
        difficulty: "Advanced",
        warmup: ["Explosive push-ups", "Light band rows", "Dynamic shoulder mobility"],
        cooldown: ["Forearm stretch", "Thoracic extension drills"],
        notes: ["Keep rest times strict to maintain intensity"],
    },
    {
        id: "lower_beginner",
        slug: "lower_beginner",
        name: "Lower Body Beginner",
        exercises: ["bodyweight-squat", "pistol-squat", "plank"],
        duration: "25 min",
        frequency: "3x per week",
        description: "A beginner-focused lower-body plan that improves leg strength, stability, and mobility. It prepares you for harder single-leg variations while keeping joints safe and movement patterns clean.",
        difficulty: "Beginner",
        warmup: ["Leg swings", "Ankle mobility", "Glute activation"],
        cooldown: ["Hamstring stretch", "Calf stretch"],
        notes: ["Prioritize knee alignment during squats"],
    },
    {
        id: "core_stability",
        slug: "core_stability",
        name: "Core & Stability",
        exercises: ["plank", "l-sit", "human-flag"],
        duration: "20 min",
        frequency: "3x per week",
        description: "A core-centered routine that strengthens your midline and stability muscles through static holds and controlled movements. Perfect for building the tension required for L-sits, flags, and other high-skill calisthenics positions.",
        difficulty: "Advanced",
        warmup: ["Hollow body rocks", "Wrist warmup", "Hip flexor activation"],
        cooldown: ["Lower back stretch", "Cat–cow"],
        notes: ["Move slowly and maintain tension throughout"],
    },
    {
        id: "push_strength",
        slug: "push_strength",
        name: "Push Strength",
        exercises: ["push-ups", "pike-push-ups", "dips", "archer-push-ups"],
        duration: "35 min",
        frequency: "3-4x per week",
        description: "A strength-focused pushing routine that targets the chest, shoulders, and triceps through progressive variations. Great for building clean reps, stronger overhead control, and better pushing mechanics.",
        difficulty: "Intermediate",
        warmup: ["Scap push-ups", "Shoulder mobility", "Wrist circles"],
        cooldown: ["Triceps stretch", "Shoulder decompression"],
        notes: ["Control the eccentric phase on every rep"],
    },
    {
        id: "pull_strength",
        slug: "pull_strength",
        name: "Pull Strength",
        exercises: ["pull-ups", "chin-ups", "muscle-up"],
        duration: "40 min",
        frequency: "3-4x per week",
        description: "A pulling-intensive routine that develops your back, biceps, forearms, and explosive pulling power. Perfect for athletes aiming to increase pull-up volume or work toward their first muscle-up.",
        difficulty: "Intermediate",
        warmup: ["Scapular pull-ups", "Dead hangs", "Band rows"],
        cooldown: ["Lat stretch", "Forearm mobility"],
        notes: ["Use false grip work if aiming for muscle-ups"],
    },
    {
        id: "planche_progression",
        slug: "planche_progression",
        name: "Planche Progression",
        exercises: ["pseudo-planche-push-up", "planche-push-ups", "planche"],
        duration: "30 min",
        frequency: "4x per week",
        description: "A targeted progression routine built to develop the strength, balance, and tendon conditioning required for planche training. Designed for slow but consistent progress through increasingly challenging holds.",
        difficulty: "Advanced",
        warmup: ["Wrist mobility routine", "Scap protraction drills"],
        cooldown: ["Forearm stretches", "Chest opening drills"],
        notes: ["Expect slow progress — be patient"],
    },
    {
        id: "handstand_focus",
        slug: "handstand_focus",
        name: "Handstand & Overhead",
        exercises: ["pike-push-ups", "wall-handstand-push-ups", "handstand-push-ups", "plank"],
        duration: "30 min",
        frequency: "3-4x per week",
        description: "A routine dedicated to overhead pressing strength, handstand stability, and shoulder endurance. Ideal for anyone working toward a controlled freestanding handstand or stronger vertical pressing.",
        difficulty: "Intermediate",
        warmup: ["Wrist prep", "Shoulder opening", "Wall line drills"],
        cooldown: ["Neck stretch", "Shoulder decompression"],
        notes: ["Focus on stacking your hips over your wrists"],
    },
    {
        id: "explosive_upper",
        slug: "explosive_upper",
        name: "Explosive Upper",
        exercises: ["muscle-up", "pull-ups", "dips", "push-ups"],
        duration: "35 min",
        frequency: "3-4x per week",
        description: "A power-oriented upper-body routine focused on speed, explosiveness, and dynamic pulling/pushing strength. Helps bridge the gap between strict reps and more advanced explosive skills like muscle-ups.",
        difficulty: "Advanced",
        warmup: ["Explosive push-ups", "Band warmup", "Shoulder activation"],
        cooldown: ["Lat stretch", "Chest opening"],
        notes: ["Use momentum sparingly—keep control"],
    },
    {
        id: "unilateral_balance",
        slug: "unilateral_balance",
        name: "Unilateral & Balance",
        exercises: ["pistol-squat", "one-arm-push-ups", "archer-push-ups", "l-sit"],
        duration: "40 min",
        frequency: "3x per week",
        description: "A single-limb strength routine emphasizing balance, stability, and unilateral control. Builds strength evenly on both sides while developing coordination for advanced calisthenics movements.",
        difficulty: "Advanced",
        warmup: ["Ankle mobility", "Shoulder prep", "Hip warmup"],
        cooldown: ["Hamstring stretch", "Glute stretch"],
        notes: ["Start with assisted variations if needed"],
    },
    {
        id: "advanced_fullbody",
        slug: "advanced_fullbody",
        name: "Advanced Full Body",
        exercises: ["planche", "human-flag", "muscle-up", "pistol-squat"],
        duration: "60 min",
        frequency: "5x per week",
        description: "A high-skill, high-intensity full-body program featuring elite-level static holds and dynamic movements. Designed for advanced athletes who already have strong fundamentals and want serious progression.",
        difficulty: "Elite",
        warmup: ["Full wrist routine", "Dynamic shoulder mobility", "Core activation"],
        cooldown: ["Full-body stretch", "Deep breathing"],
        notes: ["Only attempt if you already master fundamentals"],
    },
    {
        id: "conditioning_circuit",
        slug: "conditioning_circuit",
        name: "Conditioning Circuit",
        exercises: ["push-ups", "pull-ups", "bodyweight-squat", "plank"],
        duration: "25 min",
        frequency: "4-5x per week",
        description: "A fast-paced conditioning routine designed to improve endurance, stamina, and overall fitness. Works the entire body with minimal rest, making it ideal for fat loss and cardiovascular improvement.",
        difficulty: "Beginner",
        warmup: ["Light jogging", "Jumping jacks"],
        cooldown: ["Hamstring stretch", "Chest stretch"],
        notes: ["Try to avoid long breaks; keep heart rate up"],
    },
    {
        id: "mobility_recovery",
        slug: "mobility_recovery",
        name: "Mobility & Recovery",
        exercises: ["plank", "bodyweight-squat", "pike-push-ups"],
        duration: "20 min",
        frequency: "2-3x per week",
        description: "A low-intensity routine that improves joint mobility, reduces stiffness, and enhances recovery between heavy training days. Perfect as an active recovery session to keep your body moving smoothly.",
        difficulty: "Beginner",
        warmup: ["Light dynamic stretching"],
        cooldown: ["Deep breathing", "Full-body stretch"],
        notes: ["Ideal on rest days"],
    },
    {
        id: "grip_flag_progression",
        slug: "grip_flag_progression",
        name: "Grip & Flag Progression",
        exercises: ["human-flag", "pull-ups", "l-sit"],
        duration: "30 min",
        frequency: "3x per week",
        description: "A targeted routine building the grip strength, core tension, and pulling power needed for human flag progressions. Focuses on controlled drills that slowly improve your ability to hold and extend the body horizontally",
        difficulty: "Advanced",
        warmup: ["Wrist prep", "Dead hangs"],
        cooldown: ["Forearm stretch", "Lat stretch"],
        notes: ["Start from tucked progressions, slowly extend"],
    },
];

export default Routines;
